#!/usr/bin/env python

import sys
import numpy as np

#: sys.argv[0] is always the script name

tgr_parent_dir = "/home/bari/HWD/mounts/temp/documents/Education/[00][Thesis]/codes/Lab/Codes"
sgr_parent_dir = "/home/bari/HWD/mounts/temp/documents/Education/[00][Thesis]/codes/Lab/simulations/00_Metals/"
metal_dir = sys.argv[1]

lff_dir = "IU"
filename = "grhs.dat"
#: pair correlation function file
pcf_file = tgr_parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename

[ position, g_iu ] = np.loadtxt(pcf_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'RT'
pcf_file = tgr_parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, g_rt ] = np.loadtxt(pcf_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'SR'
pcf_file = tgr_parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, g_sr ] = np.loadtxt(pcf_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'VS'
pcf_file = tgr_parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, g_vs ] = np.loadtxt(pcf_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'FD'
pcf_file = tgr_parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, g_fd ] = np.loadtxt(pcf_file, skiprows=2, usecols=(0, 1), unpack=True)

filename = "rdf_from_trajectory.dat"
pcf_file = sgr_parent_dir + '/' + metal_dir + '/used/' + filename
[ s_position, s_g ] = np.loadtxt(pcf_file, usecols=(0, 1), unpack=True)

max_len = len(position)

fill = np.nan
s_position_padded = np.pad(s_position, (0, max_len - len(s_position)), 'constant', constant_values=fill)
s_g_padded = np.pad(s_g, (0, max_len - len(s_position)), 'constant', constant_values=fill)

gr_data_file = "gr.dat"
np.savetxt(gr_data_file, np.column_stack((position, g_iu, g_rt, g_sr, g_vs, g_fd, s_position_padded, s_g_padded)), newline='\n', fmt='%s')
