#!/usr/bin/env python

import sys
import numpy as np

#: sys.argv[0] is always the script name

parent_dir = "/home/bari/HWD/mounts/temp/documents/Education/[00][Thesis]/codes/Lab/Codes"
metal_dir = sys.argv[1]

lff_dir = "IU"
filename = "FFACTOR.DAT"
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename

[ wn, v_iu ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'RT'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ wn, v_rt ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'SR'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ wn, v_sk ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'VS'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ wn, v_vs ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'FD'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ wn, v_fd ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

vq_data_file = "vq.dat"
np.savetxt(vq_data_file, np.column_stack((wn, v_iu, v_rt, v_sk, v_vs, v_fd)), newline='\n', fmt='%s')
