#!/usr/bin/env python

import sys
import numpy as np

#: sys.argv[0] is always the script name

parent_dir = "/home/bari/HWD/mounts/temp/documents/Education/[00][Thesis]/codes/Lab/Codes"
metal_dir = sys.argv[1]

lff_dir = "IU"
filename = "BRET.DAT"
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename

[ position, v_iu ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'RT'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, v_rt ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'SR'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, v_sr ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'VS'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, v_vs ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

lff_dir = 'FD'
potential_file = parent_dir + '/' + lff_dir + '/' + metal_dir + '/' + filename
[ position, v_fd ] = np.loadtxt(potential_file, skiprows=2, usecols=(0, 1), unpack=True)

vr_data_file = "vr.dat"
np.savetxt(vr_data_file, np.column_stack((position, v_iu, v_rt, v_sr, v_vs, v_fd)), newline='\n', fmt='%s')
